# Generated by Django 3.0.7 on 2021-01-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
