# Generated by Django 3.0.7 on 2021-01-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rewiew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('published_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('new on moderation', 'Новый на модерации'),
                                                     ('published', 'Опубликован'), ('hidden', 'Скрыт')],
                                            max_length=50)),
            ],
        ),
    ]
