# Generated by Django 3.0.7 on 2021-01-12 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rewiew_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rewiew',
            old_name='content',
            new_name='text',
        ),
    ]
