# Generated by Django 3.0.7 on 2021-01-14 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20210112_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewiew',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='rewiew',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='rewiew',
            name='status',
            field=models.CharField(choices=[('new', ' На модерации'), ('published', 'Опубликован'), ('hidden', 'Скрыт')], max_length=50),
        ),
    ]
