# Generated by Django 3.0.7 on 2021-01-14 19:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20210114_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewiew',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rewiew',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
