# Generated by Django 3.0.7 on 2021-01-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20210114_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewiew',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rewiew',
            name='published_at',
            field=models.DateTimeField(),
        ),
    ]
