# Generated by Django 3.0.7 on 2021-01-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20210115_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewiew',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
